
services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5242:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d


  app:
    build: .
    container_name: meu_app_java
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}/${DB_NAME}?currentSchema=${DB_SCHEMA}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}

volumes:
  postgres_data: