spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: sch_techindustry

logging:
  level:
    org:
      hibernate:
        orm:
          connections:
            pooling: ERROR

  thymeleaf:
     cache: false

api:
  security:
    token:
      secret: ${JWT_SECRET}