spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: sch_techindustry

api:
  security:
    token:
      secret: "Z3IuMyyMse"